#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.36279
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fias.Parser
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="FIAS")]
	public partial class FiasDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public FiasDBDataContext() : 
				base(global::Fias.Parser.Properties.Settings.Default.FIASConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public FiasDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FiasDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FiasDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FiasDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<House> Houses
		{
			get
			{
				return this.GetTable<House>();
			}
		}
		
		public System.Data.Linq.Table<Object> Objects
		{
			get
			{
				return this.GetTable<Object>();
			}
		}
		
		public System.Data.Linq.Table<HouseInterval> HouseIntervals
		{
			get
			{
				return this.GetTable<HouseInterval>();
			}
		}
		
		public System.Data.Linq.Table<Landmark> Landmarks
		{
			get
			{
				return this.GetTable<Landmark>();
			}
		}
		
		public System.Data.Linq.Table<NormativeDocument> NormativeDocuments
		{
			get
			{
				return this.GetTable<NormativeDocument>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.House")]
	public partial class House
	{
		
		private string _POSTALCODE;
		
		private string _IFNSFL;
		
		private string _TERRIFNSFL;
		
		private string _IFNSUL;
		
		private string _TERRIFNSUL;
		
		private string _OKATO;
		
		private string _OKTMO;
		
		private System.DateTime _UPDATEDATE;
		
		private string _HOUSENUM;
		
		private int _ESTSTATUS;
		
		private string _BUILDNUM;
		
		private string _STRUCNUM;
		
		private System.Nullable<bool> _STRSTATUS;
		
		private string _HOUSEID;
		
		private string _HOUSEGUID;
		
		private string _AOGUID;
		
		private System.DateTime _STARTDATE;
		
		private System.DateTime _ENDDATE;
		
		private bool _STATSTATUS;
		
		private string _NORMDOC;
		
		private int _COUNTER;
		
		public House()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POSTALCODE", DbType="NVarChar(50)")]
		public string POSTALCODE
		{
			get
			{
				return this._POSTALCODE;
			}
			set
			{
				if ((this._POSTALCODE != value))
				{
					this._POSTALCODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IFNSFL", DbType="NVarChar(50)")]
		public string IFNSFL
		{
			get
			{
				return this._IFNSFL;
			}
			set
			{
				if ((this._IFNSFL != value))
				{
					this._IFNSFL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TERRIFNSFL", DbType="NVarChar(50)")]
		public string TERRIFNSFL
		{
			get
			{
				return this._TERRIFNSFL;
			}
			set
			{
				if ((this._TERRIFNSFL != value))
				{
					this._TERRIFNSFL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IFNSUL", DbType="NVarChar(50)")]
		public string IFNSUL
		{
			get
			{
				return this._IFNSUL;
			}
			set
			{
				if ((this._IFNSUL != value))
				{
					this._IFNSUL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TERRIFNSUL", DbType="NVarChar(50)")]
		public string TERRIFNSUL
		{
			get
			{
				return this._TERRIFNSUL;
			}
			set
			{
				if ((this._TERRIFNSUL != value))
				{
					this._TERRIFNSUL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OKATO", DbType="NVarChar(50)")]
		public string OKATO
		{
			get
			{
				return this._OKATO;
			}
			set
			{
				if ((this._OKATO != value))
				{
					this._OKATO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OKTMO", DbType="NVarChar(50)")]
		public string OKTMO
		{
			get
			{
				return this._OKTMO;
			}
			set
			{
				if ((this._OKTMO != value))
				{
					this._OKTMO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UPDATEDATE", DbType="DateTime NOT NULL")]
		public System.DateTime UPDATEDATE
		{
			get
			{
				return this._UPDATEDATE;
			}
			set
			{
				if ((this._UPDATEDATE != value))
				{
					this._UPDATEDATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOUSENUM", DbType="NVarChar(50)")]
		public string HOUSENUM
		{
			get
			{
				return this._HOUSENUM;
			}
			set
			{
				if ((this._HOUSENUM != value))
				{
					this._HOUSENUM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESTSTATUS", DbType="Int NOT NULL")]
		public int ESTSTATUS
		{
			get
			{
				return this._ESTSTATUS;
			}
			set
			{
				if ((this._ESTSTATUS != value))
				{
					this._ESTSTATUS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BUILDNUM", DbType="NVarChar(50)")]
		public string BUILDNUM
		{
			get
			{
				return this._BUILDNUM;
			}
			set
			{
				if ((this._BUILDNUM != value))
				{
					this._BUILDNUM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STRUCNUM", DbType="NVarChar(50)")]
		public string STRUCNUM
		{
			get
			{
				return this._STRUCNUM;
			}
			set
			{
				if ((this._STRUCNUM != value))
				{
					this._STRUCNUM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STRSTATUS", DbType="Bit")]
		public System.Nullable<bool> STRSTATUS
		{
			get
			{
				return this._STRSTATUS;
			}
			set
			{
				if ((this._STRSTATUS != value))
				{
					this._STRSTATUS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOUSEID", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string HOUSEID
		{
			get
			{
				return this._HOUSEID;
			}
			set
			{
				if ((this._HOUSEID != value))
				{
					this._HOUSEID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOUSEGUID", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string HOUSEGUID
		{
			get
			{
				return this._HOUSEGUID;
			}
			set
			{
				if ((this._HOUSEGUID != value))
				{
					this._HOUSEGUID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AOGUID", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string AOGUID
		{
			get
			{
				return this._AOGUID;
			}
			set
			{
				if ((this._AOGUID != value))
				{
					this._AOGUID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STARTDATE", DbType="DateTime NOT NULL")]
		public System.DateTime STARTDATE
		{
			get
			{
				return this._STARTDATE;
			}
			set
			{
				if ((this._STARTDATE != value))
				{
					this._STARTDATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ENDDATE", DbType="DateTime NOT NULL")]
		public System.DateTime ENDDATE
		{
			get
			{
				return this._ENDDATE;
			}
			set
			{
				if ((this._ENDDATE != value))
				{
					this._ENDDATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATSTATUS", DbType="Bit NOT NULL")]
		public bool STATSTATUS
		{
			get
			{
				return this._STATSTATUS;
			}
			set
			{
				if ((this._STATSTATUS != value))
				{
					this._STATSTATUS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NORMDOC", DbType="NVarChar(50)")]
		public string NORMDOC
		{
			get
			{
				return this._NORMDOC;
			}
			set
			{
				if ((this._NORMDOC != value))
				{
					this._NORMDOC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COUNTER", DbType="Int NOT NULL")]
		public int COUNTER
		{
			get
			{
				return this._COUNTER;
			}
			set
			{
				if ((this._COUNTER != value))
				{
					this._COUNTER = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Object")]
	public partial class Object
	{
		
		private string _AOGUID;
		
		private string _FORMALNAME;
		
		private string _REGIONCODE;
		
		private string _AUTOCODE;
		
		private string _AREACODE;
		
		private string _CITYCODE;
		
		private string _CTARCODE;
		
		private string _PLACECODE;
		
		private string _STREETCODE;
		
		private string _EXTRCODE;
		
		private string _SEXTCODE;
		
		private string _OFFNAME;
		
		private string _POSTALCODE;
		
		private string _IFNSFL;
		
		private string _TERRIFNSFL;
		
		private string _IFNSUL;
		
		private string _TERRIFNSUL;
		
		private string _OKATO;
		
		private string _OKTMO;
		
		private System.DateTime _UPDATEDATE;
		
		private string _SHORTNAME;
		
		private bool _AOLEVEL;
		
		private string _PARENTGUID;
		
		private string _AOID;
		
		private string _PREVID;
		
		private string _NEXTID;
		
		private string _CODE;
		
		private string _PLAINCODE;
		
		private bool _ACTSTATUS;
		
		private bool _CENTSTATUS;
		
		private bool _OPERSTATUS;
		
		private bool _CURRSTATUS;
		
		private System.DateTime _STARTDATE;
		
		private System.DateTime _ENDDATE;
		
		private string _NORMDOC;
		
		private short _LIVESTATUS;
		
		public Object()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AOGUID", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string AOGUID
		{
			get
			{
				return this._AOGUID;
			}
			set
			{
				if ((this._AOGUID != value))
				{
					this._AOGUID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FORMALNAME", DbType="NVarChar(120) NOT NULL", CanBeNull=false)]
		public string FORMALNAME
		{
			get
			{
				return this._FORMALNAME;
			}
			set
			{
				if ((this._FORMALNAME != value))
				{
					this._FORMALNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REGIONCODE", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string REGIONCODE
		{
			get
			{
				return this._REGIONCODE;
			}
			set
			{
				if ((this._REGIONCODE != value))
				{
					this._REGIONCODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AUTOCODE", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string AUTOCODE
		{
			get
			{
				return this._AUTOCODE;
			}
			set
			{
				if ((this._AUTOCODE != value))
				{
					this._AUTOCODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AREACODE", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string AREACODE
		{
			get
			{
				return this._AREACODE;
			}
			set
			{
				if ((this._AREACODE != value))
				{
					this._AREACODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CITYCODE", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string CITYCODE
		{
			get
			{
				return this._CITYCODE;
			}
			set
			{
				if ((this._CITYCODE != value))
				{
					this._CITYCODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CTARCODE", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string CTARCODE
		{
			get
			{
				return this._CTARCODE;
			}
			set
			{
				if ((this._CTARCODE != value))
				{
					this._CTARCODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PLACECODE", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string PLACECODE
		{
			get
			{
				return this._PLACECODE;
			}
			set
			{
				if ((this._PLACECODE != value))
				{
					this._PLACECODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STREETCODE", DbType="NVarChar(50)")]
		public string STREETCODE
		{
			get
			{
				return this._STREETCODE;
			}
			set
			{
				if ((this._STREETCODE != value))
				{
					this._STREETCODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EXTRCODE", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string EXTRCODE
		{
			get
			{
				return this._EXTRCODE;
			}
			set
			{
				if ((this._EXTRCODE != value))
				{
					this._EXTRCODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SEXTCODE", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string SEXTCODE
		{
			get
			{
				return this._SEXTCODE;
			}
			set
			{
				if ((this._SEXTCODE != value))
				{
					this._SEXTCODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OFFNAME", DbType="NVarChar(120)")]
		public string OFFNAME
		{
			get
			{
				return this._OFFNAME;
			}
			set
			{
				if ((this._OFFNAME != value))
				{
					this._OFFNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POSTALCODE", DbType="NVarChar(50)")]
		public string POSTALCODE
		{
			get
			{
				return this._POSTALCODE;
			}
			set
			{
				if ((this._POSTALCODE != value))
				{
					this._POSTALCODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IFNSFL", DbType="NVarChar(50)")]
		public string IFNSFL
		{
			get
			{
				return this._IFNSFL;
			}
			set
			{
				if ((this._IFNSFL != value))
				{
					this._IFNSFL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TERRIFNSFL", DbType="NVarChar(50)")]
		public string TERRIFNSFL
		{
			get
			{
				return this._TERRIFNSFL;
			}
			set
			{
				if ((this._TERRIFNSFL != value))
				{
					this._TERRIFNSFL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IFNSUL", DbType="NVarChar(50)")]
		public string IFNSUL
		{
			get
			{
				return this._IFNSUL;
			}
			set
			{
				if ((this._IFNSUL != value))
				{
					this._IFNSUL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TERRIFNSUL", DbType="NVarChar(50)")]
		public string TERRIFNSUL
		{
			get
			{
				return this._TERRIFNSUL;
			}
			set
			{
				if ((this._TERRIFNSUL != value))
				{
					this._TERRIFNSUL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OKATO", DbType="NVarChar(50)")]
		public string OKATO
		{
			get
			{
				return this._OKATO;
			}
			set
			{
				if ((this._OKATO != value))
				{
					this._OKATO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OKTMO", DbType="NVarChar(50)")]
		public string OKTMO
		{
			get
			{
				return this._OKTMO;
			}
			set
			{
				if ((this._OKTMO != value))
				{
					this._OKTMO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UPDATEDATE", DbType="DateTime NOT NULL")]
		public System.DateTime UPDATEDATE
		{
			get
			{
				return this._UPDATEDATE;
			}
			set
			{
				if ((this._UPDATEDATE != value))
				{
					this._UPDATEDATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SHORTNAME", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string SHORTNAME
		{
			get
			{
				return this._SHORTNAME;
			}
			set
			{
				if ((this._SHORTNAME != value))
				{
					this._SHORTNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AOLEVEL", DbType="Bit NOT NULL")]
		public bool AOLEVEL
		{
			get
			{
				return this._AOLEVEL;
			}
			set
			{
				if ((this._AOLEVEL != value))
				{
					this._AOLEVEL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PARENTGUID", DbType="NVarChar(50)")]
		public string PARENTGUID
		{
			get
			{
				return this._PARENTGUID;
			}
			set
			{
				if ((this._PARENTGUID != value))
				{
					this._PARENTGUID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AOID", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string AOID
		{
			get
			{
				return this._AOID;
			}
			set
			{
				if ((this._AOID != value))
				{
					this._AOID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PREVID", DbType="NVarChar(50)")]
		public string PREVID
		{
			get
			{
				return this._PREVID;
			}
			set
			{
				if ((this._PREVID != value))
				{
					this._PREVID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NEXTID", DbType="NVarChar(50)")]
		public string NEXTID
		{
			get
			{
				return this._NEXTID;
			}
			set
			{
				if ((this._NEXTID != value))
				{
					this._NEXTID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODE", DbType="NVarChar(50)")]
		public string CODE
		{
			get
			{
				return this._CODE;
			}
			set
			{
				if ((this._CODE != value))
				{
					this._CODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PLAINCODE", DbType="NVarChar(50)")]
		public string PLAINCODE
		{
			get
			{
				return this._PLAINCODE;
			}
			set
			{
				if ((this._PLAINCODE != value))
				{
					this._PLAINCODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACTSTATUS", DbType="Bit NOT NULL")]
		public bool ACTSTATUS
		{
			get
			{
				return this._ACTSTATUS;
			}
			set
			{
				if ((this._ACTSTATUS != value))
				{
					this._ACTSTATUS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CENTSTATUS", DbType="Bit NOT NULL")]
		public bool CENTSTATUS
		{
			get
			{
				return this._CENTSTATUS;
			}
			set
			{
				if ((this._CENTSTATUS != value))
				{
					this._CENTSTATUS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OPERSTATUS", DbType="Bit NOT NULL")]
		public bool OPERSTATUS
		{
			get
			{
				return this._OPERSTATUS;
			}
			set
			{
				if ((this._OPERSTATUS != value))
				{
					this._OPERSTATUS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CURRSTATUS", DbType="Bit NOT NULL")]
		public bool CURRSTATUS
		{
			get
			{
				return this._CURRSTATUS;
			}
			set
			{
				if ((this._CURRSTATUS != value))
				{
					this._CURRSTATUS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STARTDATE", DbType="DateTime NOT NULL")]
		public System.DateTime STARTDATE
		{
			get
			{
				return this._STARTDATE;
			}
			set
			{
				if ((this._STARTDATE != value))
				{
					this._STARTDATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ENDDATE", DbType="DateTime NOT NULL")]
		public System.DateTime ENDDATE
		{
			get
			{
				return this._ENDDATE;
			}
			set
			{
				if ((this._ENDDATE != value))
				{
					this._ENDDATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NORMDOC", DbType="NVarChar(50)")]
		public string NORMDOC
		{
			get
			{
				return this._NORMDOC;
			}
			set
			{
				if ((this._NORMDOC != value))
				{
					this._NORMDOC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LIVESTATUS", DbType="SmallInt NOT NULL")]
		public short LIVESTATUS
		{
			get
			{
				return this._LIVESTATUS;
			}
			set
			{
				if ((this._LIVESTATUS != value))
				{
					this._LIVESTATUS = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HouseInterval")]
	public partial class HouseInterval
	{
		
		private string _POSTALCODE;
		
		private string _IFNSFL;
		
		private string _TERRIFNSFL;
		
		private string _IFNSUL;
		
		private string _TERRIFNSUL;
		
		private string _OKATO;
		
		private string _OKTMO;
		
		private System.DateTime _UPDATEDATE;
		
		private bool _INTSTART;
		
		private bool _INTEND;
		
		private string _HOUSEINTID;
		
		private string _INTGUID;
		
		private string _AOGUID;
		
		private System.DateTime _STARTDATE;
		
		private System.DateTime _ENDDATE;
		
		private bool _INTSTATUS;
		
		private string _NORMDOC;
		
		private bool _COUNTER;
		
		public HouseInterval()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POSTALCODE", DbType="NVarChar(50)")]
		public string POSTALCODE
		{
			get
			{
				return this._POSTALCODE;
			}
			set
			{
				if ((this._POSTALCODE != value))
				{
					this._POSTALCODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IFNSFL", DbType="NVarChar(50)")]
		public string IFNSFL
		{
			get
			{
				return this._IFNSFL;
			}
			set
			{
				if ((this._IFNSFL != value))
				{
					this._IFNSFL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TERRIFNSFL", DbType="NVarChar(50)")]
		public string TERRIFNSFL
		{
			get
			{
				return this._TERRIFNSFL;
			}
			set
			{
				if ((this._TERRIFNSFL != value))
				{
					this._TERRIFNSFL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IFNSUL", DbType="NVarChar(50)")]
		public string IFNSUL
		{
			get
			{
				return this._IFNSUL;
			}
			set
			{
				if ((this._IFNSUL != value))
				{
					this._IFNSUL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TERRIFNSUL", DbType="NVarChar(50)")]
		public string TERRIFNSUL
		{
			get
			{
				return this._TERRIFNSUL;
			}
			set
			{
				if ((this._TERRIFNSUL != value))
				{
					this._TERRIFNSUL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OKATO", DbType="NVarChar(50)")]
		public string OKATO
		{
			get
			{
				return this._OKATO;
			}
			set
			{
				if ((this._OKATO != value))
				{
					this._OKATO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OKTMO", DbType="NVarChar(50)")]
		public string OKTMO
		{
			get
			{
				return this._OKTMO;
			}
			set
			{
				if ((this._OKTMO != value))
				{
					this._OKTMO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UPDATEDATE", DbType="DateTime NOT NULL")]
		public System.DateTime UPDATEDATE
		{
			get
			{
				return this._UPDATEDATE;
			}
			set
			{
				if ((this._UPDATEDATE != value))
				{
					this._UPDATEDATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INTSTART", DbType="Bit NOT NULL")]
		public bool INTSTART
		{
			get
			{
				return this._INTSTART;
			}
			set
			{
				if ((this._INTSTART != value))
				{
					this._INTSTART = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INTEND", DbType="Bit NOT NULL")]
		public bool INTEND
		{
			get
			{
				return this._INTEND;
			}
			set
			{
				if ((this._INTEND != value))
				{
					this._INTEND = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOUSEINTID", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string HOUSEINTID
		{
			get
			{
				return this._HOUSEINTID;
			}
			set
			{
				if ((this._HOUSEINTID != value))
				{
					this._HOUSEINTID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INTGUID", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string INTGUID
		{
			get
			{
				return this._INTGUID;
			}
			set
			{
				if ((this._INTGUID != value))
				{
					this._INTGUID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AOGUID", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string AOGUID
		{
			get
			{
				return this._AOGUID;
			}
			set
			{
				if ((this._AOGUID != value))
				{
					this._AOGUID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STARTDATE", DbType="DateTime NOT NULL")]
		public System.DateTime STARTDATE
		{
			get
			{
				return this._STARTDATE;
			}
			set
			{
				if ((this._STARTDATE != value))
				{
					this._STARTDATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ENDDATE", DbType="DateTime NOT NULL")]
		public System.DateTime ENDDATE
		{
			get
			{
				return this._ENDDATE;
			}
			set
			{
				if ((this._ENDDATE != value))
				{
					this._ENDDATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INTSTATUS", DbType="Bit NOT NULL")]
		public bool INTSTATUS
		{
			get
			{
				return this._INTSTATUS;
			}
			set
			{
				if ((this._INTSTATUS != value))
				{
					this._INTSTATUS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NORMDOC", DbType="NVarChar(50)")]
		public string NORMDOC
		{
			get
			{
				return this._NORMDOC;
			}
			set
			{
				if ((this._NORMDOC != value))
				{
					this._NORMDOC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COUNTER", DbType="Bit NOT NULL")]
		public bool COUNTER
		{
			get
			{
				return this._COUNTER;
			}
			set
			{
				if ((this._COUNTER != value))
				{
					this._COUNTER = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Landmark")]
	public partial class Landmark
	{
		
		private string _LOCATION;
		
		private string _POSTALCODE;
		
		private string _IFNSFL;
		
		private string _TERRIFNSFL;
		
		private string _IFNSUL;
		
		private string _TERRIFNSUL;
		
		private string _OKATO;
		
		private string _OKTMO;
		
		private System.DateTime _UPDATEDATE;
		
		private string _LANDID;
		
		private string _LANDGUID;
		
		private string _AOGUID;
		
		private System.DateTime _STARTDATE;
		
		private System.DateTime _ENDDATE;
		
		private string _NORMDOC;
		
		public Landmark()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOCATION", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
		public string LOCATION
		{
			get
			{
				return this._LOCATION;
			}
			set
			{
				if ((this._LOCATION != value))
				{
					this._LOCATION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POSTALCODE", DbType="NVarChar(50)")]
		public string POSTALCODE
		{
			get
			{
				return this._POSTALCODE;
			}
			set
			{
				if ((this._POSTALCODE != value))
				{
					this._POSTALCODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IFNSFL", DbType="NVarChar(50)")]
		public string IFNSFL
		{
			get
			{
				return this._IFNSFL;
			}
			set
			{
				if ((this._IFNSFL != value))
				{
					this._IFNSFL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TERRIFNSFL", DbType="NVarChar(50)")]
		public string TERRIFNSFL
		{
			get
			{
				return this._TERRIFNSFL;
			}
			set
			{
				if ((this._TERRIFNSFL != value))
				{
					this._TERRIFNSFL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IFNSUL", DbType="NVarChar(50)")]
		public string IFNSUL
		{
			get
			{
				return this._IFNSUL;
			}
			set
			{
				if ((this._IFNSUL != value))
				{
					this._IFNSUL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TERRIFNSUL", DbType="NVarChar(50)")]
		public string TERRIFNSUL
		{
			get
			{
				return this._TERRIFNSUL;
			}
			set
			{
				if ((this._TERRIFNSUL != value))
				{
					this._TERRIFNSUL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OKATO", DbType="NVarChar(50)")]
		public string OKATO
		{
			get
			{
				return this._OKATO;
			}
			set
			{
				if ((this._OKATO != value))
				{
					this._OKATO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OKTMO", DbType="NVarChar(50)")]
		public string OKTMO
		{
			get
			{
				return this._OKTMO;
			}
			set
			{
				if ((this._OKTMO != value))
				{
					this._OKTMO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UPDATEDATE", DbType="DateTime NOT NULL")]
		public System.DateTime UPDATEDATE
		{
			get
			{
				return this._UPDATEDATE;
			}
			set
			{
				if ((this._UPDATEDATE != value))
				{
					this._UPDATEDATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LANDID", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string LANDID
		{
			get
			{
				return this._LANDID;
			}
			set
			{
				if ((this._LANDID != value))
				{
					this._LANDID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LANDGUID", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string LANDGUID
		{
			get
			{
				return this._LANDGUID;
			}
			set
			{
				if ((this._LANDGUID != value))
				{
					this._LANDGUID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AOGUID", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string AOGUID
		{
			get
			{
				return this._AOGUID;
			}
			set
			{
				if ((this._AOGUID != value))
				{
					this._AOGUID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STARTDATE", DbType="DateTime NOT NULL")]
		public System.DateTime STARTDATE
		{
			get
			{
				return this._STARTDATE;
			}
			set
			{
				if ((this._STARTDATE != value))
				{
					this._STARTDATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ENDDATE", DbType="DateTime NOT NULL")]
		public System.DateTime ENDDATE
		{
			get
			{
				return this._ENDDATE;
			}
			set
			{
				if ((this._ENDDATE != value))
				{
					this._ENDDATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NORMDOC", DbType="NVarChar(50)")]
		public string NORMDOC
		{
			get
			{
				return this._NORMDOC;
			}
			set
			{
				if ((this._NORMDOC != value))
				{
					this._NORMDOC = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NormativeDocument")]
	public partial class NormativeDocument
	{
		
		private string _NORMDOCID;
		
		private string _DOCNAME;
		
		private System.Nullable<System.DateTime> _DOCDATE;
		
		private string _DOCNUM;
		
		private bool _DOCTYPE;
		
		private System.Nullable<bool> _DOCIMGID;
		
		public NormativeDocument()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NORMDOCID", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string NORMDOCID
		{
			get
			{
				return this._NORMDOCID;
			}
			set
			{
				if ((this._NORMDOCID != value))
				{
					this._NORMDOCID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOCNAME", DbType="NVarChar(MAX)")]
		public string DOCNAME
		{
			get
			{
				return this._DOCNAME;
			}
			set
			{
				if ((this._DOCNAME != value))
				{
					this._DOCNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOCDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> DOCDATE
		{
			get
			{
				return this._DOCDATE;
			}
			set
			{
				if ((this._DOCDATE != value))
				{
					this._DOCDATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOCNUM", DbType="NVarChar(50)")]
		public string DOCNUM
		{
			get
			{
				return this._DOCNUM;
			}
			set
			{
				if ((this._DOCNUM != value))
				{
					this._DOCNUM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOCTYPE", DbType="Bit NOT NULL")]
		public bool DOCTYPE
		{
			get
			{
				return this._DOCTYPE;
			}
			set
			{
				if ((this._DOCTYPE != value))
				{
					this._DOCTYPE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOCIMGID", DbType="Bit")]
		public System.Nullable<bool> DOCIMGID
		{
			get
			{
				return this._DOCIMGID;
			}
			set
			{
				if ((this._DOCIMGID != value))
				{
					this._DOCIMGID = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
